version: '3'

services:
    django:
        build: ./backend/
        container_name: backend
        command: python manage.py runserver 0.0.0.0:8585
        #command: uwsgi --socket :8001 --enable-threads --module choc.wsgi
        volumes:
        - ./backend:/app
#        ports:
#        - "8585:8585"

    react:
        #image: node:latest
        build: ./frontend/
        container_name: frontend
        volumes:
          - ./frontend/react_app:/app
        environment:
          - CHOKIDAR_USEPOLLING=true
        depends_on:
          - django


    server:
            image: nginx
            container_name: nginx
            ports:
                - "8123:8123"
            volumes:
                - ./env/nginx/:/etc/nginx/conf.d
#            links:
#              - backend
#              - frontend
            depends_on:
               - django
               - react