# Generated by Django 2.2.10 on 2020-02-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_date',)},
        ),
    ]
